Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -112,10 +112,7 @@ runs:
 
             if [[ "${{ env.PRIORITY }}" == "v2" ]]; then
               echo "url=$(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}")" 1>>$GITHUB_OUTPUT 2>$err
-              if grep -q "exit status 1" $err; then
-                  echo "The command failed"
-                  exit 1
-              fi
+
             else
               $(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}" &> /dev/null)
             fi
@@ -129,10 +126,6 @@ runs:
             oxygen_v1_command="$GITHUB_ACTION_PATH/oxygenctl deploy --health-check=${{ inputs.oxygen_health_check }}"
             if [[ "${{ env.PRIORITY }}" == "v1" ]]; then
               echo "url=$(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command)" 1>>$GITHUB_OUTPUT 2>$err
-              if grep -q "exit status 1" $err; then
-                  echo "The command failed"
-                  exit 1
-              fi
             else
               $(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command &> /dev/null)
             fi
@@ -140,3 +133,8 @@ runs:
         fi
 
         wait
+
+        if grep -q "exit status 1" $err; then
+          echo "The command failed"
+          exit 1
+        fi
