test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -111,7 +111,10 @@ runs:
 
             if [[ "${{ env.PRIORITY }}" == "v2" ]]; then
               echo "url=$(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}" && exit_status=$? )" >> $GITHUB_OUTPUT
-              [[ $exit_status -ne 0 ]] && exit 1
+              if [ $exit_status -ne 0 ]; then
+                  echo "The command failed with exit status: $exit_status"
+                  exit $exit_status
+              fi
             else
               $(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}" &> /dev/null)
             fi
@@ -125,7 +128,10 @@ runs:
             oxygen_v1_command="$GITHUB_ACTION_PATH/oxygenctl deploy --health-check=${{ inputs.oxygen_health_check }}"
             if [[ "${{ env.PRIORITY }}" == "v1" ]]; then
               echo "url=$(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command && exit_status=$? )" >> $GITHUB_OUTPUT
-              [[ $exit_status -ne 0 ]] && exit 1
+              if [ $exit_status -ne 0 ]; then
+                  echo "The command failed with exit status: $exit_status"
+                  exit $exit_status
+              fi
             else
               $(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command &> /dev/null)
             fi
