Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -110,10 +110,10 @@ runs:
                   --token=${{ steps.check_version.outputs.v2_token }}"
 
             if [[ "${{ env.PRIORITY }}" == "v2" ]]; then
-              echo "url=$(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}" && exit_status=$? )" >> $GITHUB_OUTPUT
-              if [ $exit_status -ne 0 ]; then
-                  echo "The command failed with exit status: $exit_status"
-                  exit $exit_status
+              echo "url=$(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}")" 1>>$GITHUB_OUTPUT 2>$err
+              if grep -q "exit status 1" $err; then
+                  echo "The command failed"
+                  exit 1
               fi
             else
               $(cd oxygen_v2 && ln -s ../node_modules node_modules && $oxygen_v2_command --buildCommand="${build_command_filtered}" &> /dev/null)
@@ -127,10 +127,10 @@ runs:
             [[ -z "${{ inputs.commit_timestamp }}" ]] && export OXYGEN_COMMIT_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ") || export OXYGEN_COMMIT_TIMESTAMP=${{ inputs.commit_timestamp }}
             oxygen_v1_command="$GITHUB_ACTION_PATH/oxygenctl deploy --health-check=${{ inputs.oxygen_health_check }}"
             if [[ "${{ env.PRIORITY }}" == "v1" ]]; then
-              echo "url=$(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command && exit_status=$? )" >> $GITHUB_OUTPUT
-              if [ $exit_status -ne 0 ]; then
-                  echo "The command failed with exit status: $exit_status"
-                  exit $exit_status
+              echo "url=$(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command)" 1>>$GITHUB_OUTPUT 2>>$err
+              if grep -q "exit status 1" $err; then
+                  echo "The command failed"
+                  exit 1
               fi
             else
               $(OXYGEN_DEPLOYMENT_TOKEN=${{ steps.check_version.outputs.v1_token }} $oxygen_v1_command &> /dev/null)
